name: CI
on: [push]
jobs:
  checkstyle:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Run ESLint
        run: npm run check
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Upload coverage report to Codecov
        uses: npm codecov
      - name: Run SonarCloud scanner
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
